### ISSUE TITLE
What are your arguments for the scalability of this solution though?

### ISSUE THREAD

**Issue by ghost** [cloudreach/squid-utm#2]
Giulio:

Apologies for reaching out via Github, but I could find no other way to contact you.

I was very recently considering implementing this exact combination of services (except I had planned on using CloudFormation instead of Terraform) and had all but given up until I found your blog post from Cloudreach.  Any way a couple of questions/problems arose as I moved towards actually deploying it:

1) Is containerizing the Squids _really_ a good use case of Docker?  There is only one service effectively to the entire application stack, namely: Squid.  In other words...it is not like this solution has decomposed/decoupled a monolith of which Squid was one component.  So is this really a good use case for Docker in the first place?

2) Given that high bandwidth and CPU throughput are the most important resources to have available to our proxy service isn't Fargate precisely the *wrong* solution to use?  My understanding is that it is for small-to-medium scale microservices.  So for example, if is the case with my own Squid infrastructure, the bandwidth scale could need to burst to potentially 1 - 5 Gb/s at any given time would Fargate really be a functional solution?

3) Given that network bandwidth and CPU are our chief concerns...wouldn't we simply be better off by not using some SaaS like Fargate and simply taking advantage of the closer-to-bare-metal immediacy of just straight EC2?  In other words if we're concern about network and CPU then couldn't we potentially degrade network and CPU by abstracting to not only Docker, but also Fargate?  The logic here being that every layer of abstraction we add is one layer further from bare metal (fastest bandwidth, purest CPU).

4) What are the cost comparisons of a super cool solution like this compared to just boring old EC2?  Because again it doesn't make sense if Fargate ends up being significantly more expensive.

I love the "sexiness" of it...which is why I thought of it in the first place: because it's a modern take on a classical model, which is awesome.  But could this deployment really scale to a mid-sized enterprise network?

I currently have this solution implemented with straight EC2, i.e. squid proxies behind an ELB.  Some relevant specs are:

Client Sum request counts to the ELB for the last two weeks
       -       ~10K/minute with daily, but infrequent bursts of up to ~70K/minute
       -       * once I started direct all account traffic to, say, an NLB, this traffic could double or quadruple, 
                i.e. ~40K/minute with bursts of something like 150K/minute?

Current instance bandwidth needs are:
      -        4 m4.xlarge's behind the ELB each bursting between 40Mb/s - 400Mb/s
      -        * again once I start routing traffic from other accounts and VPCs to this proposed solution of 
                course the bandwidth requirements could possibly head into the GB/s?  Or I suppose I could 
                scale horizontally more?

Sorry for the long issue, although hopefully you can appreciate my interest in getting your feedback on my thoughts here.

If you'd like to chat about this online or via email just let me know and I'll shoot you my details.

Thanks again,

Jonas Steinberg

**Comment by giuliocalzo** [comment]
Hi @jonassteinberg1 I tried to ping you in private, I will try to reply to this thread also, following the previous format structure:

1. Dockerize Squid is not really necessary, the idea is to have something ready to be deployed and portable across multiple scenarios (on-prem or other CSP), this is the reason why I chose Docker. Using a good immutable infrastructure approach you can reach the same result. Keep in mind in order to run this code in production other factors can influence the decision (some of them are for example 2,3,4 ;) )

2. as you mention Fargate is not the right tool for high bandwidth and CPU throughput, but can perfectly fit in scenario where we want to have a more "AsAService" model with low infrastructure footprint, for Squid on EC2 AWS published an [amazing article](https://aws.amazon.com/blogs/security/how-to-set-up-an-outbound-vpc-proxy-with-domain-whitelisting-and-content-filtering/) 

3. this is a basic configuration for squid as soon as you use HTTPS or any advanced feature you must choose the right compute service that fits your requirements 

4. you always need to consider COST in AWS, Fargate sometimes is not the best way for a long-running process (if you want to handle the traffic that you mention **for sure is not** the right tool) cloudonaut.io publish an amazing [article](https://cloudonaut.io/ecs-vs-fargate-whats-the-difference/) about that.
 
Regarding the pro/cons of the docker, ec2, fargate I hope my answers will make more clarity, I strongly suggest to **ALWAYS** evaluate your requirements, some solution can fit your scenario or absolute incompatible with your workload.

I would like to add one interesting consideration regarding the Load Balancer decision.
I suggest to use NLB because:
- Fixed IP (perfect when you use PROXY )
- Squid access log work out-of-the-box (with ALB you need to do some adjustment  )
- using [PrivLink](https://aws.amazon.com/blogs/apn/enabling-new-saas-strategies-with-aws-privatelink/) you can provide squid "as a service" to other AWS Accounts

 I will for sure re-use this thread and integrated into the README for a dedicated section **When to use Fargate**

**Comment by feiyao** [comment]
Giulio,
I'm not sure you are using Squid Transparent Poxy or Non-Transparent Proxy which requires clients to configure http_proxy. I assume it is Transparent. I didn't see how you configure the VPC routes in your terraform. I assume it all goes through VPC Endpoint Service.

Would you please highlight how the Transparent part is configured for Squid?
Thanks.

**Comment by giuliocalzo** [comment]
hi @feiyao this is an architecture for Non-Transparent Proxy.
you need to set the env vars in your system

```
export http_proxy='http://aws-nlb-fqdn:3128'
export https_proxy='http://aws-nlb-fqdn:3128'
```

**Comment by leocrawford** [comment]
@giuliocalzolari could you clarify what you had in mind for "with ALB you need to do some adjustment"? I was going to put proxy behind WAF which I believe only works for ALB

**Comment by ghost** [comment]
I'm glad to see other people interested in this approach because I'd like to implement myself, but I honestly have trouble justifying this as production-sane within any context beyond a fairly small environment because ECS basically charges you on a per-call basis and if you have a busy proxy environment then there will be a lot of calls unlike EC2 where you're just being charged for compute, effectively.

**Comment by leocrawford** [comment]
I tend to think you're right but I'm keen to try both and get some real data on performance and cost. If it turns out to be nothing more than a learning experience I'm content.  I also wonder if PaaS costs will reduce quicker than SaaS so you may see a cost convergence.

**Comment by giuliocalzo** [comment]
@leocrawford `with ALB you need to do some adjustment` you need to check the deregistration timeout for example. one good advantage of ALB (as you mention) is the possible integration of WAF

**Comment by leocrawford** [comment]
For info; ALB doesn't seem to work as:

1. ALB doesn't seem to support connect
3. ALB strips the host from GET requests
